### ISSUE TITLE
Implement shopping cart functionality

### ISSUE THREAD

**Issue by ajithkumar1422** [ajithskumar1609/tripSync#1]
### Description
We need to implement a shopping Cart functionality for our **Tour Booking** website. The Cart should allow users to:
- Add items to the Cart
- Get user  Cart
- Remove items from the Cart
- Calculate the total price of items in the Cart

### Tasks
- [x] Create a Cart component
- [x] Implement functionality to add items to the Cart
- [x] implement functionality get user Cart
- [x] Implement functionality to remove items from the Cart
- [x] Calculate the total price of items in the Cart

### Additional Information
This feature is critical for improving user experience and increasing conversion rates.

**Comment by ajithskumar1609** [comment]
finished the shopping cart functionality backend api

**Comment by ajithkumar1422** [comment]
finished the shopping cart functionality backend Api
