### ISSUE TITLE
Implement Wishlist Functionality

### ISSUE THREAD

**Issue by ajithkumar1422** [ajithskumar1609/tripSync#3]
### Description
We need to implement a Wishlist functionality for our **Tour Booking** website. The Wishlist should allow users to:
- Add items to the Wishlist
- Get user Wishlist
- Remove items from the Wishlist
- get total count of item in Wishlist

### Tasks
- [x] Create a Wishlist component
- [x] Implement functionality to add items to the Wishlist
- [x] implement functionality get user Wishlist 
- [x] Implement functionality to remove items from the Wishlist
- [x] implement functionality total count of item in Wishlist

### Additional Information
This feature is critical for improving user experience and increasing conversion rates.

**Comment by ajithkumar1422** [comment]
finished all the functionality
